[theme]
# Soft cream-white for a comfortable, warm background
backgroundColor = "#FBFBF9"

secondaryBackgroundColor = "#EFEFEA"

textColor = "#2a3b52"

primaryColor = "#1B365D"

font = "sans-serif"


[browser]
gatherUsageStats = false
